// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfNxpMSuLF82SKM60wkY1V5B9yBh5oMA',
    appId: '1:630923786149:web:736ddd45dc4cbd76aa1a4c',
    messagingSenderId: '630923786149',
    projectId: 'insta-x-43872',
    authDomain: 'insta-x-43872.firebaseapp.com',
    storageBucket: 'insta-x-43872.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKnWiTF_cgqFTAuFKuiWyI_9kRBsffGs',
    appId: '1:630923786149:android:5427ff0f7cf315deaa1a4c',
    messagingSenderId: '630923786149',
    projectId: 'insta-x-43872',
    storageBucket: 'insta-x-43872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyf-fRiksYC_-wLHZF01g_sOSK8U_deVU',
    appId: '1:630923786149:ios:d9fafa2bd7f05811aa1a4c',
    messagingSenderId: '630923786149',
    projectId: 'insta-x-43872',
    storageBucket: 'insta-x-43872.appspot.com',
    iosBundleId: 'com.example.instax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyf-fRiksYC_-wLHZF01g_sOSK8U_deVU',
    appId: '1:630923786149:ios:5f8450d5dfa71f25aa1a4c',
    messagingSenderId: '630923786149',
    projectId: 'insta-x-43872',
    storageBucket: 'insta-x-43872.appspot.com',
    iosBundleId: 'com.example.instax.RunnerTests',
  );
}
